app:
  HOST_IP: 127.0.0.1
  ENV: production
  APP_PORT: 8080
  ACCESS_TOKEN_EXP: 15
  REFRESH_TOKEN_EXP: 168
  JWT_SECRET: SAMPLE
  DB_TYPE: postgres
  CACHE_TYPE: redis

database:
  DB_HOST: 127.0.0.1
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres
  DB_PORT: 5555
  SSL_MODE: disable
  DB_URL: sample
  MAX_OPEN_CONNS: 500
  MAX_IDLE_CONNS: 100

cache:
  CACHE_HOST: localhost:6379
  CACHE_PASSWORD: redis
  CACHE_DB: 0
